<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '19',
    'typeid' => '0',
    'title' => '铜周评：铜价维持横盘震荡',
    'style' => '',
    'thumb' => 'http://localhost/uploadfile/2014/0512/20140512112052681.jpg',
    'keywords' => '铜价',
    'description' => '本周铜市小幅下调，长江现货铜价对比上周累计下跌405元，跌幅约为0 81%。本周乌克兰局势不断升温，国内楼市风险不减，同时国内需求转弱，多   ',
    'posids' => '1',
    'url' => 'http://localhost/html/2014/mtbd_0512/2.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1399864827',
    'updatetime' => '1399889107',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '19',
    'typeid' => '0',
    'title' => '证券日报：上期所利用有色指数期货拓展风险管理空间',
    'style' => '',
    'thumb' => '',
    'keywords' => '风险管理 期货 指数',
    'description' => '本周市场多空叠加，美国公布经济数据喜忧参半，耶伦在联储会议上论调谨慎，维持宽松预期，美元大幅回落，但对大宗商品提振有限；欧洲多国公   ',
    'posids' => '1',
    'url' => 'http://localhost/html/2014/mtbd_0512/1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1399863763',
    'updatetime' => '1399864682',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '20',
    'typeid' => '0',
    'title' => 'sdfsadf',
    'style' => '',
    'thumb' => '',
    'keywords' => 'sdfsadf',
    'description' => 'asdfasdfasdf',
    'posids' => '0',
    'url' => 'http://localhost/html/2014/zxdt_0710/3.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1404955024',
    'updatetime' => '1404955028',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>