<?php
return array (
  'Name' => 
  array (
    'fieldid' => '108',
    'modelid' => '14',
    'siteid' => '1',
    'field' => 'Name',
    'name' => '姓名',
    'tips' => '请输入姓名',
    'css' => 'form_guide',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '姓名输入错误！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'email' => 
  array (
    'fieldid' => '109',
    'modelid' => '14',
    'siteid' => '1',
    'field' => 'email',
    'name' => '邮箱',
    'tips' => '请输入邮箱',
    'css' => 'form_guide',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[\\w\\-\\.]+@[\\w\\-\\.]+(\\.\\w+)+$/',
    'errortips' => '请输入正确的邮箱！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'qq' => 
  array (
    'fieldid' => '110',
    'modelid' => '14',
    'siteid' => '1',
    'field' => 'qq',
    'name' => 'qq',
    'tips' => '请输入qq号码',
    'css' => 'form_guide',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '请输入正确的qq号码！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'phone' => 
  array (
    'fieldid' => '111',
    'modelid' => '14',
    'siteid' => '1',
    'field' => 'phone',
    'name' => '电话',
    'tips' => '请输入电话号码',
    'css' => 'form_guide',
    'minlength' => '6',
    'maxlength' => '0',
    'pattern' => '/^[0-9-]{6,13}$/',
    'errortips' => '请输入正确的电话号码！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'liuyan' => 
  array (
    'fieldid' => '112',
    'modelid' => '14',
    'siteid' => '1',
    'field' => 'liuyan',
    'name' => '留言',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入正确的留言',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>