<?php
return array (
  'Name' => 
  array (
    'fieldid' => '113',
    'modelid' => '16',
    'siteid' => '1',
    'field' => 'Name',
    'name' => '姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入正确的姓名！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'email' => 
  array (
    'fieldid' => '114',
    'modelid' => '16',
    'siteid' => '1',
    'field' => 'email',
    'name' => '邮箱',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[\\w\\-\\.]+@[\\w\\-\\.]+(\\.\\w+)+$/',
    'errortips' => '请输入正确的邮箱！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'qq' => 
  array (
    'fieldid' => '119',
    'modelid' => '16',
    'siteid' => '1',
    'field' => 'qq',
    'name' => 'qq',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'phone' => 
  array (
    'fieldid' => '116',
    'modelid' => '16',
    'siteid' => '1',
    'field' => 'phone',
    'name' => '电话',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[0-9-]{6,13}$/',
    'errortips' => '请输入正确的电话号码！',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'25\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '25',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'liuyan' => 
  array (
    'fieldid' => '117',
    'modelid' => '16',
    'siteid' => '1',
    'field' => 'liuyan',
    'name' => '留言',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入正确的留言!',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'50%\',
  \'height\' => \'100\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '50%',
    'height' => '100',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>